### ISSUE TITLE
File Download Crash

### ISSUE THREAD

**Issue by mukyasa** [scazzy/facebook-workplace-app#1]
Hey scazzy,

Thanks for creating this project, would be great if you can fix the file download crash, whenever i try downloading any kind of file the app crashes.

Thanks again

**Comment by scazzy** [comment]
@mukyasa thanks for feedback. Do you see any error before the crash? if so, can you share the error?

**Comment by Howe73** [comment]
I can reproduce this error as well. As soon as I click the download link it pops this error message up
![image](https://user-images.githubusercontent.com/29869870/27802836-cf576c9c-5feb-11e7-9922-5d13ee1e4308.png)

and not sure if it is related. But if I click on the preview button, it pops open a new blank window with nothing in it.

**Comment by scazzy** [comment]
@Howe73 there's a bug. Will work on it soon. But the error shouldn't restrict from downloading file. After you close all error alerts, the file will be downloaded automatically.

**Comment by Howe73** [comment]
Thanks for the info. To tell you the truth, I haven't had a need to download anything yet (we are only a couple weeks using workplace). I was just trying to reproduce the error to give you the result.

But good to know!

**Comment by scazzy** [comment]
@mukyasa 
The bug is fixed. You can download fresh copies and replace the old ones.
Download links: https://github.com/scazzy/facebook-workplace-app
