### ISSUE TITLE
Sierra 10.12.4

### ISSUE THREAD

**Issue by tjaussoin-luna** [scazzy/facebook-workplace-app#2]
Hi, after I try to sign in, I have a white page. I run macOS Sierra 10.12.4.
Thanks for your help.

**Comment by scazzy** [comment]
Could try refresh? Command + R? or restart the app. Let me know if works

**Comment by scazzy** [comment]
You can download fresh copies and replace the old ones.
Download links: https://github.com/scazzy/facebook-workplace-app
