### ISSUE TITLE
Windows App Starts in Chat

### ISSUE THREAD

**Issue by Howe73** [scazzy/facebook-workplace-app#3]
Windows Version: Windows 10 v1703
App Version: 1.1.3.0

When you launch the app, it loads the Chat and not the main home page. You can easily click the home link, but figured the desired intent is to launch the main screen.

**Comment by scazzy** [comment]
@Howe73 I kept the chat to be the launch page as primary behavior is the work chat communication for most companies to give a Slack like behavior.

**Comment by Howe73** [comment]
@scazzy  Thanks for the information.
If I can provide a counter argument. 
- if you browse to their main page workplace.fb.com it launches the main screen and not the chat. So it would make sense to have the Facebook workplace app do the same. Besides, you can have the best of both worlds because of the chat window on the bottom right hand of the app has it

- I see your point about the slack like behavior. But workplace handles this differently. Slack has channels and each channel has its own separate chat, whereas the closest thing in workplace to that is Groups. At least when I was using Slack, I very rarely slacked a particular person, but slacked a channel. I see Workplace Chat more like Slack Direct Messages, which is not the focus of Slack (IMO)

- On mobile, Facebook decided to split the main app and chat into 2 separate programs: Workplace and Work Chat. So the intention, at least on mobile, is if you want to use Workplace, it will launch the main screen and if you want to chat then you would use a separate program

If I could suggest switching it to workplace.fb.com or provide a command switch/config file/setting to give us the option, that would be more appreciated.

Does the Mac app perform similarly? and any feedback? I could very well be in the minority ;)

**Comment by scazzy** [comment]
@Howe73 Thanks for hinting out. The app is updated and now has 2 versions. One is Workplace that launches Workplace by default, and the other is WorkChat, which launches Chat by default. Use either as required.

You can download fresh copies and replace the old ones.
Download links: https://github.com/scazzy/facebook-workplace-app
