### ISSUE TITLE
Default Landing Page

### ISSUE THREAD

**Issue by imlizin** [scazzy/facebook-workplace-app#5]
Every time i open the app it brings be to Ticklemedia's Facebook Workplace instead (https://tickledmedia.facebook.com/work/login?next=https%3A%2F%2Ftickledmedia.facebook.com%2Fchat%2Ft%2F), and I would have to go back to the main page to log in again.

Can we make it save my log in so I won't have to log in each time?
![screen shot 2017-07-08 at 1 05 27 pm](https://user-images.githubusercontent.com/19794080/27982765-70670a98-63de-11e7-815e-2dcd6d7355b5.png)

**Comment by scazzy** [comment]
@imlizin thanks for noticing. I'll update in next release.
But regardless, you can directly log in using your company email address.
